[package]
name = "contact_server2"
version = "0.1.0"
authors = ["Jane Lusby <jlusby42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
eyre = "0.3.5"
